app/scripts/app.js
I had this same error with https://jsconsole.com - after the user installed to their homescreen, when the app is launched, it asks to install again (snapdrop had the same issue).
This small tweak fixes it (though I'm not familiar with the polymer component, and I suspect I've done it in a non-polymer way - but it should still work).
Cheers so much - this app is my first real world install of a PWA - great work!
=> fix: don't display install banner when installed

README.md, gulpfile.js, package.json
- Update link to binaryjs, as their website seems to be down
- Update Material Design link
- Replace `gulp-minify-css` and `gulp-minify-html`, they have been deprecated
- Update ws [#1](https://nodesecurity.io/advisories/ws_buffer-leak), [#2](https://nodesecurity.io/advisories/socketio_dos-due-to-excessively-large-websocket-message)
=> Update broken/moved links, package deps, and gulpfile

gulpfile.js, tasks/ensure-files.js
This fixes the issue where `gulp serve` would just fail.
The code is extremely messy, and tasks like `gulp html`, `gulp lint`, and `gulp vulcanize` have not been fixed yet.
=> Temporary fixes to reproducing a proper `gulp serve`

client/scripts/network.js
When setting up a WebRTC connection between two clients, the `onServerMessage()` method gets called twice - once with a WebRTC offer, and once with the answer to the offer. Calling `createAnswer()` only works in the browser that is receiving the offer. This PR avoids calling `createAnswer()` when an answer has just been received.
=> Fix bug where clients try to re-answer established connections.

server/index.js
While testing for #74, I had a problem where Firefox and Safari were using different IPv6 addresses for localhost (`::1` and `::ffff:127.0.0.1`, although I don't know which is which). This PR separates the room name into a separate variable and sets it to the same value for all common `localhost` addresses (`127.0.0.1`, `::1`, and `::ffff:127.0.0.1`).
=> Make IPv4 and IPv6 localhost connections use the same room.

client/scripts/ui.js
This is a simple implementation of automatically sending a pasted screen clip to the one peer that is connected.  I didn't implement a UI for selecting the recipient peer in the even that multiple are connected, but maybe this could be a start.
=> Paste image item from clipboard

client/manifest.json
Changed `display: "minimal-ui"` to `"standalone"`. There doesn't seem to be any reason to keep the `minimal-ui`: no need for a browser back button or similar. This change will also now allow Chrome on mobile to show the Add to Home Screen banner, which does not show with `minimal-ui`.
Fixes #93
=> Enable standalone display mode (PWA)

client/manifest.json
Unfortunately, standalone breaks image download on iOS
=> Revert "Enable standalone display mode (PWA)"

client/index.html
Fixes broken FAQ link which currently returns Not Found. 
BTW the server image probably needs to be updated (after merging this PR) as currently the link to the _new_ FAQ page isn't there at all, but still the old one which points to the README...
=> Fix broken FAQ link

client/index.html
I've changed this because the original message can be intended as an option, not a simple information.
Updated, because the message is not appropriate. https://github.com/RobinLinus/snapdrop/pull/192#discussion_r541861110
View #191.
=> Changed "discover" message - Updated

server/index.js
Currently, server run by `node index.js` is not able to handle SIGTERM or SIGINT properly. The only fate is being killed. This change adds basic handling logic for these two signals, helping server to behave more properly as expected by many daemons and users.
=> Add support for SIGINT and SIGTERM handling

client/scripts/network.js
I am not really sure if this is the right way or what, but I am
unable to send nor receive files on a Windows 10 computer, but my
other devices (not Windows 10) can use snapdrop just fine.
Using the unified plan SDP Semantics I got snapdrop to work, the
other option is 'plan b', but I don't know much about this.
The following issues might be related to this: #177 #164 #168 #171 #186 #188 #190
This stackoverflow post made me test this:
https://stackoverflow.com/questions/55378987/failed-to-execute-setremotedescription-on-rtcpeerconnection-failed-to-set-r
=> Assign a default SDP Semantics

client/index.html, client/scripts/ui.js, client/styles.css
As stated in Issue #202 the textarea in the chat (dialog) window does not auto-expand. 
The height of the textarea is statically set. This is makes writing messages longer than a few words quite inconvenient. At the moment a sidebar appears to allow scrolling of longer messages.
The problem is inherent to the use of the `textarea` HTML tag, which doesn't allow automatic "expansion".
The desired Behaviour (an auto-expanding textarea) can be achieved by using a contenteditable div. This is exactly what this change does. 
The `textarea` HTML tag is substituted by a "contenteditable" `div`. This `div `shares all of the properties (style and HTML attributes) of the current `textarea` tag. The new `div` shares the functionalities of the current tag as well (ui.js has been edited to mirror …
=> Resolves #202

client/scripts/ui.js
I've changed the timeout time from 1000ms to 1750ms because, when there is someone already connected to Snapdrop, when Snapdrop is loaded by a portrait mode device, the time is not enough to view the background effect in all the screen.
Below an iPad example:
=> Updated ui.js animation stop timeout because of a bad show on portrait mode

README.md
Docker is the name for a technology. Therefore, the name should be capitalized as a proper noun.
=> Capitalize "d" in "Docker"

client/scripts/network.js
This change makes snapdrop client look for its web socket relative to where the client page was served from, this makes it so the client can be proxied from URLs other than /.  It's needed so that the client can be proxied by home assistant (which exposes the container under a path and /server does not work to find the socket).
=> Make socket location relative to location snapdrop client was served from

client/scripts/network.js
[fa1ff95](https://github.com/RobinLinus/snapdrop/commit/fa1ff959656ead380ed99c9955b9648506538e8c) just prevents receiver receiving data, but the sender are still sending data.
The real bug may be file-end-check function `isFileEnd ` in class `FileChunker`.
=> fix bug: sender endlessly sends empty data

client/styles.css
The previous version of Snapdrop with images preview, had a bug when transferring big (vertical) images that hided download button. These changes should resolve the issue (I'm not very expert with CSS, if anyone have some proposes, let me know).
Closes #338 and #352.
=> Resolve image too big bug modifying style

README.md
Was directing to German Wiki.
Fixes #407
=> Fixes #407 PWA Wiki Link German Issue

client/scripts/network.js
In some browsers like Firefox, when making an answer peer they define `channel.binaryType` as a `blob`
So when receiving a chunk, the chunk type is delivered as a `blob`, not as `arraybuffer` which causes many problems while sending & receiving
I think this could close many opening issues related to Firefox & transferring problems, #347  #373  #401 #466 #469 #503 #506
=> Fix transferring issue

client/index.html
This is just a minor fix, but I found that the /'s before sounds break reverse proxying into a subfolder with traefik.
It doesn't break any existing functionality and works in the context I tested.
I was initially  using [linuxserver/snapdrop](https://github.com/linuxserver/docker-snapdrop/packages) but then I edited the Dockerfiles to make the build work.
added this line to the Dockerfile
`sed -i 's#/sounds#sounds#g' /app/www/client/index.html && \`
I have tested it on arm64 (raspberry pi 4b+) and amd64.
=> Removeing the unecessary / 's in index.html as it breaks reverse proxying into a sub folder.

client/styles.css
Depending on the image the preview is bigger that the containing ReceiveDialog. This PR fixes this.
Successor of #539 
Before:
After:
=> [bug] fix image overflow

client/manifest.json
Without this, if the user add snapdrop isn't on root pass `http://myserver.local/snapdrop` to the home screen, then when click on the icon, it will go to `http://myserver.local` instead.
=> Fix manifest if snapdrop isn't on root path

client/scripts/ui.js
Without this change, I have this error (snapdrop is hosted on https://xxxx/snapdrop)
=> Removed the / of service-worker.js as it breaks reverse proxying
